name: Deploy to Firebase
on: 
	push:
		branches:
			- main

jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - run: npm run build
      - run: npm run deploy

