name: Deploy to Firebase
on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Checking out respository
        uses: actions/checkout@main

      - name: Setting up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Installing dependencies
        run: npm i

      - name: Building package
        run: npm run build

      - name: Deploying to Firebase
        run: |
          yarn deploy --token=${{ secrets.SNARKJS_MPC_FIREBASE_HOSTING }}

